name: WordPress CI Workflow

on:
  push:
    branches:
      - master
      - 'feature/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'

    - name: Install dependencies
      run: composer install

    - name: Run Coding Standards Check
      run: composer phpcs -p -- --standard=phpcs.xml

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t retr0man99/wordpress-app:latest .
        docker push retr0man99/wordpress-app:latest